<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>LaptopRequisition.WebAPI</RootNamespace> <!-- Corrected this line -->
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.10" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.25" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.*">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
        <PackageReference Include="Refit" Version="7.0.0" /> <!-- Added this line -->
        <PackageReference Include="Refit.HttpClientFactory" Version="7.0.0" /> <!-- Added this line -->
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\LaptopRequisition.Application\LaptopRequisition.Application.csproj" />
      <ProjectReference Include="..\LaptopRequisition.Infrastructure\LaptopRequisition.Infrastructure.csproj" />
    </ItemGroup>

</Project>